
eval "$(/opt/homebrew/bin/brew shellenv)"
alias sdkmanager=/opt/android_sdk/cmdline-tools/latest/bin/sdkmanager
# Created by `pipx` on 2025-06-09 02:28:32
export PATH="$PATH:/Users/samjackson/.local/bin"
